version: '3.8'

services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspaces:cached
      - cargo-cache:/usr/local/cargo/registry
      - target-cache:/workspaces/target
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/rust_app
    depends_on:
      postgres:
        condition: service_healthy
    command: sleep infinity
    networks:
      - dev-network

  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: rust_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - dev-network

volumes:
  postgres-data:
  cargo-cache:
  target-cache:

networks:
  dev-network:
    driver: bridge